services:
  backend:
    image: ${DOCKERHUB_USERNAME:-raelqiansyah}/bedifie:${IMAGE_TAG:-latest}
    container_name: bedifie-backend
    restart: unless-stopped
    environment:
      - PORT=${PORT:-4000}
      - DB_HOST=${DB_HOST:-dbdifie.cgxgc8wsgidd.us-east-1.rds.amazonaws.com}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-admin}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-dbdifie}
      - DB_CONNECT_TIMEOUT=${DB_CONNECT_TIMEOUT:-10000}
      - DB_SSL=${DB_SSL:-false}
      - DB_SSL_REJECT_UNAUTHORIZED=${DB_SSL_REJECT_UNAUTHORIZED:-true}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://98.80.187.179}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME:-bucket-difie}
    ports:
      - "4000:4000"
