import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  plugins: [forms, containerQueries],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffefec",
        "primary-fixed-dim": "#90e28a",
        "on-tertiary-fixed-variant": "#5e2c00",
        secondary: "#495f69",
        "on-tertiary-container": "#502400",
        "on-tertiary": "#fff0e8",
        "inverse-primary": "#9df197",
        "surface-bright": "#f5f6f7",
        "on-tertiary-fixed": "#2b1100",
        primary: "#176a21",
        "on-primary-fixed-variant": "#12661e",
        "on-secondary-fixed": "#2d424c",
        "on-background": "#2c2f30",
        "on-surface-variant": "#595c5d",
        "inverse-surface": "#0c0f10",
        "surface-dim": "#d1d5d7",
        "secondary-dim": "#3e535c",
        "on-secondary-fixed-variant": "#495f69",
        "on-primary": "#d1ffc8",
        "on-secondary-container": "#40555f",
        "surface-container-low": "#eff1f2",
        "on-secondary": "#e4f5ff",
        background: "#f5f6f7",
        "surface-variant": "#dadddf",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#fc820c",
        "surface-tint": "#176a21",
        "tertiary-fixed": "#ff9647",
        tertiary: "#914700",
        "surface-container-high": "#e0e3e4",
        "surface-container-highest": "#dadddf",
        "secondary-fixed-dim": "#c1d8e4",
        error: "#b02500",
        "primary-fixed": "#9df197",
        "surface-container": "#e6e8ea",
        "tertiary-container": "#ff9647",
        "secondary-container": "#cfe6f2",
        surface: "#f5f6f7",
        "primary-container": "#9df197",
        "error-container": "#f95630",
        "on-surface": "#2c2f30",
        "on-primary-fixed": "#00460e",
        "tertiary-dim": "#7f3d00",
        "secondary-fixed": "#cfe6f2",
        "error-dim": "#b92902",
        "inverse-on-surface": "#9b9d9e",
        "outline-variant": "#abadae",
        "on-primary-container": "#005c15",
        outline: "#757778",
        "primary-dim": "#025d16",
        "on-error-container": "#520c00",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "Manrope", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        label: ["var(--font-inter)", "Inter", "sans-serif"],
        manrope: ["var(--font-manrope)", "Manrope", "sans-serif"],
        inter: ["var(--font-inter)", "Inter", "sans-serif"],
      },
    },
  },
};

export default config;
