CREATE DATABASE IF NOT EXISTS `user_crud` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `user_crud`;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
