services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: /api
    container_name: fedifie-frontend
    restart: unless-stopped
    environment:
      - PORT=3000
    expose:
      - "3000"
    networks:
      - fedifie-fe-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: fedifie-nginx
    restart: unless-stopped
    depends_on:
      - frontend
    ports:
      - "80:80"
    networks:
      - fedifie-fe-network

networks:
  fedifie-fe-network:
    driver: bridge
